services:
  bot:
    container_name: "CEX.IO-bot"
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 1"
    volumes:
      - ./sessions:/app/sessions
      - ./do_not_commit.proxies.json:/app/do_not_commit.proxies.json
    env_file:
      - .env
